<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class NeighborhoodTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('neighborhoods')->delete();

        DB::table('neighborhoods')->insert([
            0 => [
                'id' => '1',
                'city_id' => '1',
                'name' => 'Centro',
                'slug' => 'centro',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            1 => [
                'id' => '2',
                'city_id' => '1',
                'name' => 'Gamboa',
                'slug' => 'gamboa',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            2 => [
                'id' => '3',
                'city_id' => '1',
                'name' => 'Santo Cristo',
                'slug' => 'santo-cristo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            3 => [
                'id' => '4',
                'city_id' => '1',
                'name' => 'Caju',
                'slug' => 'caju',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            4 => [
                'id' => '5',
                'city_id' => '1',
                'name' => 'Catumbi',
                'slug' => 'catumbi',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            5 => [
                'id' => '6',
                'city_id' => '1',
                'name' => 'Rio Comprido',
                'slug' => 'rio-comprido',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            6 => [
                'id' => '7',
                'city_id' => '1',
                'name' => 'Cidade Nova',
                'slug' => 'cidade-nova',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            7 => [
                'id' => '8',
                'city_id' => '1',
                'name' => 'Estácio',
                'slug' => 'estacio',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            8 => [
                'id' => '9',
                'city_id' => '1',
                'name' => 'Flamengo',
                'slug' => 'flamengo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            9 => [
                'id' => '10',
                'city_id' => '1',
                'name' => 'Glória',
                'slug' => 'gloria',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            10 => [
                'id' => '11',
                'city_id' => '1',
                'name' => 'Laranjeiras',
                'slug' => 'laranjeiras',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            11 => [
                'id' => '12',
                'city_id' => '1',
                'name' => 'Catete',
                'slug' => 'catete',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            12 => [
                'id' => '13',
                'city_id' => '1',
                'name' => 'Cosme Velho',
                'slug' => 'cosme-velho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            13 => [
                'id' => '14',
                'city_id' => '1',
                'name' => 'Botafogo',
                'slug' => 'botafogo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            14 => [
                'id' => '15',
                'city_id' => '1',
                'name' => 'Urca',
                'slug' => 'urca',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            15 => [
                'id' => '16',
                'city_id' => '1',
                'name' => 'Humaitá',
                'slug' => 'humaita',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            16 => [
                'id' => '17',
                'city_id' => '1',
                'name' => 'Leme',
                'slug' => 'leme',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            17 => [
                'id' => '18',
                'city_id' => '1',
                'name' => 'Copacabana',
                'slug' => 'copacabana',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            18 => [
                'id' => '19',
                'city_id' => '1',
                'name' => 'Ipanema',
                'slug' => 'ipanema',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            19 => [
                'id' => '20',
                'city_id' => '1',
                'name' => 'Leblon',
                'slug' => 'leblon',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            20 => [
                'id' => '21',
                'city_id' => '1',
                'name' => 'Lagoa',
                'slug' => 'lagoa',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            21 => [
                'id' => '22',
                'city_id' => '1',
                'name' => 'jardim-botanico',
                'slug' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            22 => [
                'id' => '23',
                'city_id' => '1',
                'name' => 'Gávea',
                'slug' => 'gavea',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            23 => [
                'id' => '24',
                'city_id' => '1',
                'name' => 'Vidigal',
                'slug' => 'vidigal',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            24 => [
                'id' => '25',
                'city_id' => '1',
                'name' => 'São Conrado',
                'slug' => 'sao-conrado',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            25 => [
                'id' => '26',
                'city_id' => '1',
                'name' => 'São Cristóvão',
                'slug' => 'sao-cristovao',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            26 => [
                'id' => '27',
                'city_id' => '1',
                'name' => 'Mangueira',
                'slug' => 'mangueira',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            27 => [
                'id' => '28',
                'city_id' => '1',
                'name' => 'Benfica',
                'slug' => 'benfica',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            28 => [
                'id' => '29',
                'city_id' => '1',
                'name' => 'Praça da Bandeira',
                'slug' => 'praca-da-bandeira',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            29 => [
                'id' => '30',
                'city_id' => '1',
                'name' => 'Tijuca',
                'slug' => 'tijuca',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            30 => [
                'id' => '31',
                'city_id' => '1',
                'name' => 'Alto da Boa Vista',
                'slug' => 'alto-da-boa-vista',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            31 => [
                'id' => '32',
                'city_id' => '1',
                'name' => 'Maracanã',
                'slug' => 'maracana',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            32 => [
                'id' => '33',
                'city_id' => '1',
                'name' => 'Vila Isabel',
                'slug' => 'vila-isabel',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            33 => [
                'id' => '34',
                'city_id' => '1',
                'name' => 'Andaraí',
                'slug' => 'andarai',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            34 => [
                'id' => '35',
                'city_id' => '1',
                'name' => 'Grajaú',
                'slug' => 'grajau',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            35 => [
                'id' => '36',
                'city_id' => '1',
                'name' => 'Manguinhos',
                'slug' => 'manguinhos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            36 => [
                'id' => '37',
                'city_id' => '1',
                'name' => 'Bonsucesso',
                'slug' => 'bonsucesso',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            37 => [
                'id' => '38',
                'city_id' => '1',
                'name' => 'Ramos',
                'slug' => 'ramos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            38 => [
                'id' => '39',
                'city_id' => '1',
                'name' => 'Olaria',
                'slug' => 'olaria',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            39 => [
                'id' => '40',
                'city_id' => '1',
                'name' => 'Penha Circular',
                'slug' => 'penha-circular',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            40 => [
                'id' => '41',
                'city_id' => '1',
                'name' => 'Brás de Pina',
                'slug' => 'bras-de-pina',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            41 => [
                'id' => '42',
                'city_id' => '1',
                'name' => 'Cordovil',
                'slug' => 'cordovil',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            42 => [
                'id' => '43',
                'city_id' => '1',
                'name' => 'Parada de Lucas',
                'slug' => 'parada-de-lucas',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            43 => [
                'id' => '44',
                'city_id' => '1',
                'name' => 'Vigário Geral',
                'slug' => 'vigario-geral',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            44 => [
                'id' => '45',
                'city_id' => '1',
                'name' => 'Jardim América',
                'slug' => 'jardim-america',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            45 => [
                'id' => '46',
                'city_id' => '1',
                'name' => 'São Francisco Xavier',
                'slug' => 'sao-francisco-xavier',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            46 => [
                'id' => '47',
                'city_id' => '1',
                'name' => 'Rocha',
                'slug' => 'rocha',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            47 => [
                'id' => '48',
                'city_id' => '1',
                'name' => 'Riachuelo',
                'slug' => 'riachuelo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            48 => [
                'id' => '49',
                'city_id' => '1',
                'name' => 'Sampaio',
                'slug' => 'sampaio',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            49 => [
                'id' => '50',
                'city_id' => '1',
                'name' => 'Engenho Novo',
                'slug' => 'engenho-novo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            50 => [
                'id' => '51',
                'city_id' => '1',
                'name' => 'Lins de Vasconcelos',
                'slug' => 'lins-de-vasconcelos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            51 => [
                'id' => '52',
                'city_id' => '1',
                'name' => 'Méier',
                'slug' => 'meier',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            52 => [
                'id' => '53',
                'city_id' => '1',
                'name' => 'Todos os Santos',
                'slug' => 'todos-os-santos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            53 => [
                'id' => '54',
                'city_id' => '1',
                'name' => 'Cachambi',
                'slug' => 'cachambi',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            54 => [
                'id' => '55',
                'city_id' => '1',
                'name' => 'Engenho de Dentro',
                'slug' => 'engenho-de-dentro',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            55 => [
                'id' => '56',
                'city_id' => '1',
                'name' => 'Água Santa',
                'slug' => 'agua-santa',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            56 => [
                'id' => '57',
                'city_id' => '1',
                'name' => 'Encantado',
                'slug' => 'encantado',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            57 => [
                'id' => '58',
                'city_id' => '1',
                'name' => 'Piedade',
                'slug' => 'piedade',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            58 => [
                'id' => '59',
                'city_id' => '1',
                'name' => 'Abolição',
                'slug' => 'abolicao',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            59 => [
                'id' => '60',
                'city_id' => '1',
                'name' => 'Pilares',
                'slug' => 'pilares',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            60 => [
                'id' => '61',
                'city_id' => '1',
                'name' => 'Vila Kosmos',
                'slug' => 'vila-kosmos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            61 => [
                'id' => '62',
                'city_id' => '1',
                'name' => 'Vicente de Carvalho',
                'slug' => 'vicente-de-carvalho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            62 => [
                'id' => '63',
                'city_id' => '1',
                'name' => 'Vila da Penha',
                'slug' => 'vila-da-penha',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            63 => [
                'id' => '64',
                'city_id' => '1',
                'name' => 'Vista Alegre',
                'slug' => 'vista-alegre',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            64 => [
                'id' => '65',
                'city_id' => '1',
                'name' => 'Irajá',
                'slug' => 'iraja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            65 => [
                'id' => '66',
                'city_id' => '1',
                'name' => 'Colégio',
                'slug' => 'colegio',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            66 => [
                'id' => '67',
                'city_id' => '1',
                'name' => 'Campinho',
                'slug' => 'campinho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            67 => [
                'id' => '68',
                'city_id' => '1',
                'name' => 'Quintino Bocaiúva',
                'slug' => 'quintino-bocaiuva',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            68 => [
                'id' => '69',
                'city_id' => '1',
                'name' => 'Cavalcanti',
                'slug' => 'cavalcanti',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            69 => [
                'id' => '70',
                'city_id' => '1',
                'name' => 'Engenheiro Leal',
                'slug' => 'engenheiro-leal',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            70 => [
                'id' => '71',
                'city_id' => '1',
                'name' => 'Cascadura',
                'slug' => 'cascadura',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            71 => [
                'id' => '72',
                'city_id' => '1',
                'name' => 'Madureira',
                'slug' => 'madureira',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            72 => [
                'id' => '73',
                'city_id' => '1',
                'name' => 'Vaz Lobo',
                'slug' => 'vaz-lobo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            73 => [
                'id' => '74',
                'city_id' => '1',
                'name' => 'Turiaçu',
                'slug' => 'turiacu',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            74 => [
                'id' => '75',
                'city_id' => '1',
                'name' => 'Rocha Miranda',
                'slug' => 'rocha-miranda',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            75 => [
                'id' => '76',
                'city_id' => '1',
                'name' => 'Honório Gurgel',
                'slug' => 'honorio-gurgel',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            76 => [
                'id' => '77',
                'city_id' => '1',
                'name' => 'Oswaldo Cruz',
                'slug' => 'oswaldo-cruz',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            77 => [
                'id' => '78',
                'city_id' => '1',
                'name' => 'Bento Ribeiro',
                'slug' => 'bento-ribeiro',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            78 => [
                'id' => '79',
                'city_id' => '1',
                'name' => 'Marechal Hermes',
                'slug' => 'marechal-hermes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            79 => [
                'id' => '80',
                'city_id' => '1',
                'name' => 'Jacarepaguá',
                'slug' => 'jacarepagua',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            80 => [
                'id' => '81',
                'city_id' => '1',
                'name' => 'Anil',
                'slug' => 'anil',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            81 => [
                'id' => '82',
                'city_id' => '1',
                'name' => 'Gardênia Azul',
                'slug' => 'gardenia-azul',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            82 => [
                'id' => '83',
                'city_id' => '1',
                'name' => 'Cidade de Deus',
                'slug' => 'cidade-de-deus',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            83 => [
                'id' => '84',
                'city_id' => '1',
                'name' => 'Curicica',
                'slug' => 'curicica',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            84 => [
                'id' => '85',
                'city_id' => '1',
                'name' => 'Freguesia - Jacarepaguá',
                'slug' => 'freguesia-jacarepagua',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            85 => [
                'id' => '86',
                'city_id' => '1',
                'name' => 'Pechincha',
                'slug' => 'pechincha',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            86 => [
                'id' => '87',
                'city_id' => '1',
                'name' => 'Taquara',
                'slug' => 'taquara',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            87 => [
                'id' => '88',
                'city_id' => '1',
                'name' => 'Tanque',
                'slug' => 'tanque',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            88 => [
                'id' => '89',
                'city_id' => '1',
                'name' => 'praca-seca',
                'slug' => '',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            89 => [
                'id' => '90',
                'city_id' => '1',
                'name' => 'Vila Valqueire',
                'slug' => 'vila-valqueire',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            90 => [
                'id' => '91',
                'city_id' => '1',
                'name' => 'Deodoro',
                'slug' => 'deodoro',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            91 => [
                'id' => '92',
                'city_id' => '1',
                'name' => 'Vila Militar',
                'slug' => 'vila-militar',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            92 => [
                'id' => '93',
                'city_id' => '1',
                'name' => 'Campo dos Afonsos',
                'slug' => 'campo-dos-afonsos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            93 => [
                'id' => '94',
                'city_id' => '1',
                'name' => 'Jardim Sulacap',
                'slug' => 'jardim-sulacap',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            94 => [
                'id' => '95',
                'city_id' => '1',
                'name' => 'Magalhães Bastos',
                'slug' => 'magalhaes-bastos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            95 => [
                'id' => '96',
                'city_id' => '1',
                'name' => 'Realengo',
                'slug' => 'realengo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            96 => [
                'id' => '97',
                'city_id' => '1',
                'name' => 'Padre Miguel',
                'slug' => 'padre-miguel',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            97 => [
                'id' => '98',
                'city_id' => '1',
                'name' => 'Bangu',
                'slug' => 'bangu',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            98 => [
                'id' => '99',
                'city_id' => '1',
                'name' => 'Senador Camará',
                'slug' => 'senador-camara',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            99 => [
                'id' => '100',
                'city_id' => '1',
                'name' => 'Santíssimo',
                'slug' => 'santissimo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            100 => [
                'id' => '101',
                'city_id' => '1',
                'name' => 'Campo Grande',
                'slug' => 'campo-grande',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            101 => [
                'id' => '102',
                'city_id' => '1',
                'name' => 'Senador Vasconcelos',
                'slug' => 'senador-vasconcelos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            102 => [
                'id' => '103',
                'city_id' => '1',
                'name' => 'Inhoaíba',
                'slug' => 'inhoaiba',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            103 => [
                'id' => '104',
                'city_id' => '1',
                'name' => 'Cosmos',
                'slug' => 'cosmos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            104 => [
                'id' => '105',
                'city_id' => '1',
                'name' => 'Paciência',
                'slug' => 'paciencia',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            105 => [
                'id' => '106',
                'city_id' => '1',
                'name' => 'Santa Cruz',
                'slug' => 'santa-cruz',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            106 => [
                'id' => '107',
                'city_id' => '1',
                'name' => 'Sepetiba',
                'slug' => 'sepetiba',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            107 => [
                'id' => '108',
                'city_id' => '1',
                'name' => 'Ribeira',
                'slug' => 'ribeira',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            108 => [
                'id' => '109',
                'city_id' => '1',
                'name' => 'Zumbi',
                'slug' => 'zumbi',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            109 => [
                'id' => '110',
                'city_id' => '1',
                'name' => 'Cacuia',
                'slug' => 'cacuia',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            110 => [
                'id' => '111',
                'city_id' => '1',
                'name' => 'Pitangueiras',
                'slug' => 'pitangueiras',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            111 => [
                'id' => '112',
                'city_id' => '1',
                'name' => 'Praia da Bandeira',
                'slug' => 'praia-da-bandeira',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            112 => [
                'id' => '113',
                'city_id' => '1',
                'name' => 'Cocotá',
                'slug' => 'cocota',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            113 => [
                'id' => '114',
                'city_id' => '1',
                'name' => 'Bancários',
                'slug' => 'bancarios',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            114 => [
                'id' => '115',
                'city_id' => '1',
                'name' => 'Freguesia - Ilha do Governador',
                'slug' => 'freguesia-ilha-do-governador',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            115 => [
                'id' => '116',
                'city_id' => '1',
                'name' => 'Jardim Guanabara',
                'slug' => 'jardim-guanabara',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            116 => [
                'id' => '117',
                'city_id' => '1',
                'name' => 'Jardim Carioca',
                'slug' => 'jardim-carioca',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            117 => [
                'id' => '118',
                'city_id' => '1',
                'name' => 'Tauá',
                'slug' => 'taua',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            118 => [
                'id' => '119',
                'city_id' => '1',
                'name' => 'Moneró',
                'slug' => 'monero',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            119 => [
                'id' => '120',
                'city_id' => '1',
                'name' => 'Portuguesa',
                'slug' => 'portuguesa',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            120 => [
                'id' => '121',
                'city_id' => '1',
                'name' => 'Galeão',
                'slug' => 'galeao',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            121 => [
                'id' => '122',
                'city_id' => '1',
                'name' => 'Cidade Universitária',
                'slug' => 'cidade-universitaria',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            122 => [
                'id' => '123',
                'city_id' => '1',
                'name' => 'Guadalupe',
                'slug' => 'guadalupe',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            123 => [
                'id' => '124',
                'city_id' => '1',
                'name' => 'Anchieta',
                'slug' => 'anchieta',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            124 => [
                'id' => '125',
                'city_id' => '1',
                'name' => 'Parque Anchieta',
                'slug' => 'parque-anchieta',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            125 => [
                'id' => '126',
                'city_id' => '1',
                'name' => 'Ricardo de Albuquerque',
                'slug' => 'ricardo-de-albuquerque',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            126 => [
                'id' => '127',
                'city_id' => '1',
                'name' => 'Santa Teresa',
                'slug' => 'santa-teresa',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            127 => [
                'id' => '128',
                'city_id' => '1',
                'name' => 'Joá',
                'slug' => 'joa',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            128 => [
                'id' => '129',
                'city_id' => '1',
                'name' => 'Itanhangá',
                'slug' => 'itanhanga',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            129 => [
                'id' => '130',
                'city_id' => '1',
                'name' => 'Barra da Tijuca',
                'slug' => 'barra-da-tijuca',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            130 => [
                'id' => '131',
                'city_id' => '1',
                'name' => 'Camorim',
                'slug' => 'camorim',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            131 => [
                'id' => '132',
                'city_id' => '1',
                'name' => 'Vargem Pequena',
                'slug' => 'vargem-pequena',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            132 => [
                'id' => '133',
                'city_id' => '1',
                'name' => 'Vargem Grande',
                'slug' => 'vargem-grande',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            133 => [
                'id' => '134',
                'city_id' => '1',
                'name' => 'Recreio dos Bandeirantes',
                'slug' => 'recreio-dos-bandeirantes',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            134 => [
                'id' => '135',
                'city_id' => '1',
                'name' => 'Grumari',
                'slug' => 'grumari',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            135 => [
                'id' => '136',
                'city_id' => '1',
                'name' => 'Coelho Neto',
                'slug' => 'coelho-neto',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            136 => [
                'id' => '137',
                'city_id' => '1',
                'name' => 'Acari',
                'slug' => 'acari',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            137 => [
                'id' => '138',
                'city_id' => '1',
                'name' => 'Barros Filho',
                'slug' => 'barros-filho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            138 => [
                'id' => '139',
                'city_id' => '1',
                'name' => 'Costa Barros',
                'slug' => 'costa-barros',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            139 => [
                'id' => '140',
                'city_id' => '1',
                'name' => 'Pavuna',
                'slug' => 'pavuna',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            140 => [
                'id' => '141',
                'city_id' => '1',
                'name' => 'Guaratiba',
                'slug' => 'guaratiba',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            141 => [
                'id' => '142',
                'city_id' => '1',
                'name' => 'Barra de Guaratiba',
                'slug' => 'barra-de-guaratiba',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            142 => [
                'id' => '143',
                'city_id' => '1',
                'name' => 'Pedra de Guaratiba',
                'slug' => 'pedra-de-guaratiba',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            143 => [
                'id' => '144',
                'city_id' => '1',
                'name' => 'Higienópolis',
                'slug' => 'higienopolis',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            144 => [
                'id' => '145',
                'city_id' => '1',
                'name' => 'Jacaré',
                'slug' => 'jacare',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            145 => [
                'id' => '146',
                'city_id' => '1',
                'name' => 'Maria da Graça',
                'slug' => 'maria-da-graca',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            146 => [
                'id' => '147',
                'city_id' => '1',
                'name' => 'Del Castilho',
                'slug' => 'del-castilho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            147 => [
                'id' => '148',
                'city_id' => '1',
                'name' => 'Inhaúma',
                'slug' => 'inhauma',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            148 => [
                'id' => '149',
                'city_id' => '1',
                'name' => 'Engenho da Rainha',
                'slug' => 'engenho-da-rainha',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            149 => [
                'id' => '150',
                'city_id' => '1',
                'name' => 'Tomás Coelho',
                'slug' => 'tomas-coelho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            150 => [
                'id' => '151',
                'city_id' => '1',
                'name' => 'Saúde',
                'slug' => 'saude',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            151 => [
                'id' => '152',
                'city_id' => '1',
                'name' => 'Paquetá',
                'slug' => 'paqueta',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            152 => [
                'id' => '153',
                'city_id' => '1',
                'name' => 'Parque Columbia',
                'slug' => 'parque-columbia',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            153 => [
                'id' => '154',
                'city_id' => '1',
                'name' => 'Jacarezinho',
                'slug' => 'jacarezinho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            154 => [
                'id' => '155',
                'city_id' => '1',
                'name' => 'Rocinha',
                'slug' => 'rocinha',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            155 => [
                'id' => '156',
                'city_id' => '1',
                'name' => 'Complexo do Alemão',
                'slug' => 'complexo-do-alemao',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            156 => [
                'id' => '157',
                'city_id' => '1',
                'name' => 'Maré',
                'slug' => 'mare',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            157 => [
                'id' => '158',
                'city_id' => '1',
                'name' => 'Vasco da Gama',
                'slug' => 'vasco-da-gama',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            158 => [
                'id' => '159',
                'city_id' => '1',
                'name' => 'Gericinó',
                'slug' => 'gericino',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
