<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SubcategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('subcategories')->delete();

        \DB::table('subcategories')->insert([
            0 => [
                'id' => '1',
                'name' => 'Berçario',
                'slug' => 'bercario',
                'internal_subcategory' => 'Berçario',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            1 => [
                'id' => '2',
                'name' => 'Maternal I',
                'slug' => 'maternal-i',
                'internal_subcategory' => 'Maternal I',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            2 => [
                'id' => '3',
                'name' => 'Maternal II',
                'slug' => 'maternal-ii',
                'internal_subcategory' => 'Maternal II',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            3 => [
                'id' => '4',
                'name' => 'Pré I',
                'slug' => 'pre-i',
                'internal_subcategory' => 'Pré I',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            4 => [
                'id' => '5',
                'name' => 'Pré II',
                'slug' => 'pre-ii',
                'internal_subcategory' => 'Pré II',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            5 => [
                'id' => '6',
                'name' => '1º ano',
                'slug' => '1-ano',
                'internal_subcategory' => '1º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            6 => [
                'id' => '7',
                'name' => '2º ano',
                'slug' => '2-ano',
                'internal_subcategory' => '2º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            7 => [
                'id' => '8',
                'name' => '3º ano',
                'slug' => '3-ano',
                'internal_subcategory' => '3º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            8 => [
                'id' => '9',
                'name' => '4º ano',
                'slug' => '4-ano',
                'internal_subcategory' => '4º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            9 => [
                'id' => '10',
                'name' => '5º ano',
                'slug' => '5-ano',
                'internal_subcategory' => '5º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            10 => [
                'id' => '11',
                'name' => '5º ano vestibulinho',
                'slug' => '5-ano-vestibulinho',
                'internal_subcategory' => '5º ano vestibulinho',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            11 => [
                'id' => '12',
                'name' => '6º ano',
                'slug' => '6-ano',
                'internal_subcategory' => '6º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            12 => [
                'id' => '13',
                'name' => '7º ano',
                'slug' => '7-ano',
                'internal_subcategory' => '7º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            13 => [
                'id' => '14',
                'name' => '8º ano',
                'slug' => '8-ano',
                'internal_subcategory' => '8º ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            14 => [
                'id' => '15',
                'name' => '9º ano',
                'slug' => '9-ano',
                'internal_subcategory' => '9-ano',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            15 => [
                'id' => '16',
                'name' => '8º ano preparatório',
                'slug' => '8-ano-preparatorio',
                'internal_subcategory' => '8º ano preparatório',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            16 => [
                'id' => '17',
                'name' => '8º ano preparatório 2',
                'slug' => '8-ano-preparatorio-2',
                'internal_subcategory' => '8º ano preparatório 2',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            17 => [
                'id' => '18',
                'name' => '1ª série',
                'slug' => '1-serie',
                'internal_subcategory' => '1ª série',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            18 => [
                'id' => '19',
                'name' => '2ª série',
                'slug' => '2-serie',
                'internal_subcategory' => '2ª série',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            19 => [
                'id' => '20',
                'name' => '3ª série',
                'slug' => '3-serie',
                'internal_subcategory' => '3ª série',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            20 => [
                'id' => '21',
                'name' => '1ª série preparatório',
                'slug' => '1-serie-preparatorio',
                'internal_subcategory' => '1ª série preparatório',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            21 => [
                'id' => '22',
                'name' => '2ª série preparatório',
                'slug' => '2-serie-preparatorio',
                'internal_subcategory' => '2ª série preparatório',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            22 => [
                'id' => '23',
                'name' => '2ª série pré militar',
                'slug' => '2-serie-pre-militar',
                'internal_subcategory' => '2ª série pré militar',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            23 => [
                'id' => '24',
                'name' => '3ª série preparatório',
                'slug' => '3-serie-preparatorio',
                'internal_subcategory' => '3ª série preparatório',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            24 => [
                'id' => '25',
                'name' => '3ª série pré enem',
                'slug' => '3-serie-pre-enem',
                'internal_subcategory' => '3ª série pré enem',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            25 => [
                'id' => '26',
                'name' => '3ª série pre vestibular',
                'slug' => '3-serie-pre-vestibular',
                'internal_subcategory' => '3ª série pre vestibular',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            26 => [
                'id' => '27',
                'name' => '3ª série + técnico em enfermagem',
                'slug' => '3-serie-tecnico-em-enfernagem',
                'internal_subcategory' => '3ª série + técnico em enfermagem',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            27 => [
                'id' => '28',
                'name' => '3ª série + técnico em administração',
                'slug' => '3-serie-tecnico-em-administracao',
                'internal_subcategory' => '3ª série + técnico em administração',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            28 => [
                'id' => '29',
                'name' => '3ª série + técnico em informática',
                'slug' => '3-serie-tecnico-em-informatica',
                'internal_subcategory' => '3ª série + técnico em informática',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            29 => [
                'id' => '30',
                'name' => 'Técnico em informática',
                'slug' => 'tecnico-em-informatica',
                'internal_subcategory' => 'Técnico em informática',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            30 => [
                'id' => '31',
                'name' => 'Ténico em Radiologia',
                'slug' => 'tecnico-em-radiologia',
                'internal_subcategory' => 'Ténico em Radiologia',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            31 => [
                'id' => '32',
                'name' => 'Técnico em Contabilidade',
                'slug' => 'tecnico-em-contabilidade',
                'internal_subcategory' => 'Técnico em Contabilidade',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            32 => [
                'id' => '33',
                'name' => 'Inspetor Predial',
                'slug' => 'inspetor-predial',
                'internal_subcategory' => 'Inspetor Predial',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            33 => [
                'id' => '34',
                'name' => 'Teatro',
                'slug' => 'teatro',
                'internal_subcategory' => 'Teatro',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            34 => [
                'id' => '35',
                'name' => 'Pré Enem',
                'slug' => 'pre-enem',
                'internal_subcategory' => 'Pré Enem',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            35 => [
                'id' => '36',
                'name' => 'Pré Vestibular',
                'slug' => 'pre-vestibular',
                'internal_subcategory' => 'Pré Vestibular',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            36 => [
                'id' => '37',
                'name' => 'Pré Enem Intensivo',
                'slug' => 'pre-enem-intensivo',
                'internal_subcategory' => 'Pré Enem Intensivo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            37 => [
                'id' => '38',
                'name' => 'Pré Naval',
                'slug' => 'pre-naval',
                'internal_subcategory' => 'Pré Naval',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            38 => [
                'id' => '39',
                'name' => 'Pré Aeronautica',
                'slug' => 'pre-aeronautica',
                'internal_subcategory' => 'Pré Aeronautica',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            39 => [
                'id' => '40',
                'name' => 'Pré Concurso',
                'slug' => 'pre-concurso',
                'internal_subcategory' => 'Pré Concurso',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            40 => [
                'id' => '41',
                'name' => 'Administração',
                'slug' => 'admistracao',
                'internal_subcategory' => 'Administração',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            41 => [
                'id' => '42',
                'name' => 'Direito',
                'slug' => 'direito',
                'internal_subcategory' => 'Direito',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            42 => [
                'id' => '43',
                'name' => 'Marketing',
                'slug' => 'marketing',
                'internal_subcategory' => 'Marketing',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            43 => [
                'id' => '44',
                'name' => 'Musica',
                'slug' => 'musica',
                'internal_subcategory' => 'Musica',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            44 => [
                'id' => '45',
                'name' => 'Psicologia',
                'slug' => 'psicologia',
                'internal_subcategory' => 'Psicologia',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            45 => [
                'id' => '46',
                'name' => 'Marketing Digital',
                'slug' => 'marketing-digital',
                'internal_subcategory' => 'Marketing Digital',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            46 => [
                'id' => '47',
                'name' => 'Direito Civil',
                'slug' => 'direito-civil',
                'internal_subcategory' => 'Direito Civil',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            47 => [
                'id' => '48',
                'name' => 'Gestão de Projetos',
                'slug' => 'gestao-de-projetos',
                'internal_subcategory' => 'Gestão de Projetos',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            48 => [
                'id' => '49',
                'name' => 'Inglês',
                'slug' => 'ingles',
                'internal_subcategory' => 'Inglês',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            49 => [
                'id' => '50',
                'name' => 'Inglês Técnico',
                'slug' => 'ingles-tecnico',
                'internal_subcategory' => 'Inglês Técnico',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            50 => [
                'id' => '51',
                'name' => 'Inglês Kids',
                'slug' => 'ingles-kids',
                'internal_subcategory' => 'Inglês Kids',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            51 => [
                'id' => '52',
                'name' => 'Ingles Intensivo',
                'slug' => 'ingles-intensivo',
                'internal_subcategory' => 'Ingles Intensivo',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            52 => [
                'id' => '53',
                'name' => 'Francês',
                'slug' => 'frances',
                'internal_subcategory' => 'Francês',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            53 => [
                'id' => '54',
                'name' => 'Mandarim',
                'slug' => 'mandarim',
                'internal_subcategory' => 'Mandarim',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            54 => [
                'id' => '55',
                'name' => 'Espanhol',
                'slug' => 'espanhol',
                'internal_subcategory' => 'Espanhol',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            55 => [
                'id' => '56',
                'name' => '6º ano',
                'slug' => '6-ano-eja',
                'internal_subcategory' => '6º ano eja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            56 => [
                'id' => '57',
                'name' => '7º ano',
                'slug' => '7-ano-eja',
                'internal_subcategory' => '7º ano eja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            57 => [
                'id' => '58',
                'name' => '8º ano',
                'slug' => '8-ano-eja',
                'internal_subcategory' => '8º ano eja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            58 => [
                'id' => '59',
                'name' => '9º ano',
                'slug' => '9-ano-eja',
                'internal_subcategory' => '9º ano eja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            59 => [
                'id' => '60',
                'name' => '1ª série',
                'slug' => '1-serie-eja',
                'internal_subcategory' => '1ª série eja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            60 => [
                'id' => '61',
                'name' => '2ª série',
                'slug' => '2-serie-eja',
                'internal_subcategory' => '2ª série eja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            61 => [
                'id' => '62',
                'name' => '3ª série',
                'slug' => '3-serie-eja',
                'internal_subcategory' => '3ª série eja',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
